2024-09-17 15:10:37,235 - app - INFO - Added student: {'age': 21, 'id': 1, 'name': 'John Doe'}
2024-09-17 15:10:37,243 - app - INFO - Retrieved all students
2024-09-17 15:10:37,249 - app - INFO - Retrieved student 3: {'age': 25, 'id': 3, 'name': 'Jim Doe'}
2024-09-17 15:10:37,257 - app - INFO - Updated student 4: {'age': 31, 'id': 4, 'name': 'Jack Updated'}
2024-09-17 15:10:37,265 - app - INFO - Deleted student 5
2024-09-17 15:34:03,620 - app - INFO - Added student: {'age': 21, 'id': 1, 'name': 'John Doe'}
2024-09-17 15:34:03,628 - app - INFO - Retrieved all students
2024-09-17 15:34:03,634 - app - INFO - Retrieved student 3: {'age': 25, 'id': 3, 'name': 'Jim Doe'}
2024-09-17 15:34:03,640 - app - INFO - Updated student 4: {'age': 31, 'id': 4, 'name': 'Jack Updated'}
2024-09-17 15:34:03,648 - app - INFO - Deleted student 5
2024-09-18 11:14:39,900 - app - INFO - Added student: {'age': 21, 'id': 5, 'name': 'John Doe'}
2024-09-18 11:14:39,912 - app - INFO - Retrieved all students
2024-09-18 11:14:39,920 - app - INFO - Retrieved student 7: {'age': 25, 'id': 7, 'name': 'Jim Doe'}
2024-09-18 11:14:39,930 - app - INFO - Updated student 8: {'age': 31, 'id': 8, 'name': 'Jack Updated'}
2024-09-18 11:14:39,940 - app - INFO - Deleted student 9
2024-09-18 11:17:09,894 - app - INFO - Added student: {'age': 21, 'id': 1, 'name': 'John Doe'}
2024-09-18 11:17:09,905 - app - INFO - Retrieved all students
2024-09-18 11:17:09,916 - app - INFO - Retrieved student 3: {'age': 25, 'id': 3, 'name': 'Jim Doe'}
2024-09-18 11:17:09,935 - app - INFO - Updated student 4: {'age': 31, 'id': 4, 'name': 'Jack Updated'}
2024-09-18 11:17:09,956 - app - INFO - Deleted student 5
2024-09-19 14:55:08,110 - app - INFO - Added student: {'age': 21, 'id': 9, 'name': 'John Doe'}
2024-09-19 14:55:08,117 - app - INFO - Retrieved all students
2024-09-19 14:55:08,123 - app - INFO - Retrieved student 11: {'age': 25, 'id': 11, 'name': 'Jim Doe'}
2024-09-19 14:55:08,132 - app - INFO - Updated student 12: {'age': 31, 'id': 12, 'name': 'Jack Updated'}
2024-09-19 14:55:08,141 - app - INFO - Deleted student 13
2024-09-19 15:42:25,508 - app - INFO - Added student: {'age': 21, 'id': 14, 'name': 'John Doe'}
2024-09-19 15:42:25,516 - app - INFO - Retrieved all students
2024-09-19 15:42:25,526 - app - INFO - Retrieved student 16: {'age': 25, 'id': 16, 'name': 'Jim Doe'}
2024-09-19 15:42:25,534 - app - INFO - Updated student 17: {'age': 31, 'id': 17, 'name': 'Jack Updated'}
2024-09-19 15:42:25,543 - app - INFO - Deleted student 18
2024-09-19 15:56:33,729 - app - INFO - Added student: {'age': 21, 'id': 19, 'name': 'John Doe'}
2024-09-19 15:56:33,737 - app - INFO - Retrieved all students
2024-09-19 15:56:33,744 - app - INFO - Retrieved student 21: {'age': 25, 'id': 21, 'name': 'Jim Doe'}
2024-09-19 15:56:33,753 - app - INFO - Updated student 22: {'age': 31, 'id': 22, 'name': 'Jack Updated'}
2024-09-19 15:56:33,763 - app - INFO - Deleted student 23
2024-09-19 18:08:54,771 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 13, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-19 18:08:54,776 - app - INFO - Retrieved all students
2024-09-19 18:08:54,777 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 13, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-19 18:08:54,783 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 13, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-19 18:08:54,788 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 13, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-19 18:15:10,090 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 13, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-19 18:15:10,094 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 13, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-19 18:19:53,177 - app - INFO - Deleted student 33
2024-09-19 19:00:08,340 - app - INFO - Deleted student 36
2024-09-19 19:00:37,680 - app - INFO - Deleted student 39
2024-09-19 19:20:33,351 - app - INFO - Deleted student 42
2024-09-19 19:24:47,724 - app - INFO - Added student with phone number: 1234567890
2024-09-19 19:24:47,792 - app - INFO - Deleted student 46
2024-09-19 19:25:16,698 - app - INFO - Added student with phone number: 1234567890
2024-09-19 19:25:16,702 - app - INFO - Added student with phone number: 5551234
2024-09-19 19:25:16,748 - app - INFO - Deleted student 50
2024-09-19 19:25:29,644 - app - INFO - Added student with phone number: 1234567890
2024-09-19 19:25:29,647 - app - INFO - Added student with phone number: 5551234
2024-09-19 19:25:29,659 - app - INFO - Updated student 53: {'age': 31, 'id': 53, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-19 19:25:29,667 - app - INFO - Deleted student 54
2024-09-19 19:40:50,019 - app - INFO - Added student with phone number: 1234567890
2024-09-19 19:40:50,023 - app - INFO - Added student with phone number: 5551234
2024-09-19 19:40:50,036 - app - INFO - Updated student 57: {'age': 31, 'id': 57, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-19 19:40:50,045 - app - INFO - Deleted student 58
2024-09-19 19:42:11,743 - app - INFO - Added student with phone number: 1234567890
2024-09-19 19:42:11,748 - app - INFO - Added student with phone number: 5551234
2024-09-19 19:42:11,759 - app - INFO - Updated student 3: {'age': 31, 'id': 3, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-19 19:42:11,767 - app - INFO - Deleted student 4
2024-09-20 14:31:08,622 - app - INFO - Added student with phone number: 1234567890
2024-09-20 14:31:08,627 - app - INFO - Added student with phone number: 5551234
2024-09-20 14:31:08,639 - app - INFO - Updated student 7: {'age': 31, 'id': 7, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-20 14:31:08,648 - app - INFO - Deleted student 8
2024-09-20 14:36:04,328 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-20 14:36:04,346 - app - INFO - Added student with phone number: 1234567890
2024-09-20 14:36:04,351 - app - INFO - Added student with phone number: 5551234
2024-09-20 14:36:04,361 - app - INFO - Updated student 11: {'age': 31, 'id': 11, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-20 14:36:04,371 - app - INFO - Deleted student 12
2024-09-20 14:42:33,001 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-20 14:42:33,022 - app - INFO - Added student with phone number: 1234567890
2024-09-20 14:42:33,063 - app - INFO - Updated student 15: {'age': 31, 'id': 15, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-20 14:42:33,074 - app - INFO - Deleted student 16
2024-09-20 14:43:15,843 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-20 14:43:15,868 - app - INFO - Added student with phone number: 1234567890
2024-09-20 14:43:15,908 - app - INFO - Updated student 19: {'age': 31, 'id': 19, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-20 14:43:15,917 - app - INFO - Deleted student 20
2024-09-20 14:44:08,654 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-20 14:44:08,667 - app - INFO - Added student with phone number: 1234567890
2024-09-20 14:44:08,707 - app - INFO - Updated student 23: {'age': 31, 'id': 23, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-20 14:44:08,718 - app - INFO - Deleted student 24
2024-09-20 14:45:08,658 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-20 14:45:08,673 - app - INFO - Added student with phone number: 1234567890
2024-09-20 14:45:08,680 - app - INFO - Retrieved student: {'age': 21, 'id': 26, 'name': 'Rajesh', 'phone_number': 1234567890}
2024-09-20 14:45:08,690 - app - INFO - Updated student 27: {'age': 31, 'id': 27, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-20 14:45:08,702 - app - INFO - Deleted student 28
2024-09-20 14:48:24,388 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-20 14:48:24,399 - app - INFO - Added student with phone number: 1234567890
2024-09-20 14:48:24,423 - app - INFO - Retrieved student: {'age': 21, 'id': 30, 'name': 'Rajesh', 'phone_number': 1234567890}
2024-09-20 14:48:24,434 - app - INFO - Updated student 31: {'age': 31, 'id': 31, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-20 14:48:24,444 - app - INFO - Deleted student 32
2024-09-20 14:49:37,718 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-20 14:49:37,728 - app - INFO - Added student with phone number: 1234567890
2024-09-20 14:49:37,735 - app - INFO - Retrieved student: {'age': 21, 'id': 34, 'name': 'Rajesh', 'phone_number': 1234567890}
2024-09-20 14:49:37,747 - app - INFO - Updated student 35: {'age': 31, 'id': 35, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-20 14:49:37,759 - app - INFO - Deleted student 36
2024-09-20 14:49:49,034 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-20 14:49:49,043 - app - INFO - Added student with phone number: 1234567890
2024-09-20 14:49:49,050 - app - INFO - Retrieved student: {'age': 21, 'id': 38, 'name': 'Rajesh', 'phone_number': 1234567890}
2024-09-20 14:49:49,060 - app - INFO - Updated student 39: {'age': 31, 'id': 39, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-20 14:49:49,072 - app - INFO - Deleted student 40
2024-09-20 15:10:56,956 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-20 15:10:56,965 - app - INFO - Added student with phone number: 1234567890
2024-09-20 15:10:56,972 - app - INFO - Retrieved student: {'age': 21, 'id': 50, 'name': 'Rajesh', 'phone_number': 1234567890}
2024-09-20 15:10:56,983 - app - INFO - Updated student 51: {'age': 31, 'id': 51, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-20 15:10:56,995 - app - INFO - Deleted student 52
2024-09-25 07:00:48,608 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-25 07:00:48,617 - app - INFO - Added student with phone number: 1234567890
2024-09-25 07:00:48,628 - app - INFO - Retrieved student: {'age': 21, 'id': 2, 'name': 'Rajesh', 'phone_number': 1234567890}
2024-09-25 07:00:48,639 - app - INFO - Updated student 3: {'age': 31, 'id': 3, 'name': 'Jack Updated', 'phone_number': 5559999}
2024-09-25 07:00:48,653 - app - INFO - Deleted student 4
2024-09-25 07:26:48,674 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-25 07:26:48,677 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'gender' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 14, in add_student
    db.session.commit()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1048, "Column 'gender' cannot be null")
[SQL: INSERT INTO student (name, age, phone_number, gender) VALUES (%(name)s, %(age)s, %(phone_number)s, %(gender)s)]
[parameters: {'name': 'Rajesh', 'age': 21, 'phone_number': '1234567890', 'gender': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-09-25 07:26:48,710 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'gender' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 14, in add_student
    db.session.commit()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1048, "Column 'gender' cannot be null")
[SQL: INSERT INTO student (name, age, phone_number, gender) VALUES (%(name)s, %(age)s, %(phone_number)s, %(gender)s)]
[parameters: {'name': 'Rajesh', 'age': 21, 'phone_number': '1234567890', 'gender': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-09-25 07:26:48,716 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'gender' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 14, in add_student
    db.session.commit()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1048, "Column 'gender' cannot be null")
[SQL: INSERT INTO student (name, age, phone_number, gender) VALUES (%(name)s, %(age)s, %(phone_number)s, %(gender)s)]
[parameters: {'name': 'Jack Doe', 'age': 30, 'phone_number': '1234567890', 'gender': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-09-25 07:26:48,722 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'gender' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 14, in add_student
    db.session.commit()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1048, "Column 'gender' cannot be null")
[SQL: INSERT INTO student (name, age, phone_number, gender) VALUES (%(name)s, %(age)s, %(phone_number)s, %(gender)s)]
[parameters: {'name': 'Jill Doe', 'age': 27, 'phone_number': '1234567890', 'gender': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-09-28 20:51:47,434 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-28 20:51:47,440 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'phone_number' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 14, in add_student
    db.session.commit()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'phone_number' in 'field list'")
[SQL: INSERT INTO student (name, age, phone_number, gender, address) VALUES (%(name)s, %(age)s, %(phone_number)s, %(gender)s, %(address)s)]
[parameters: {'name': 'Rajesh', 'age': 21, 'phone_number': '1234567890', 'gender': None, 'address': None}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-09-28 20:51:47,509 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'phone_number' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 14, in add_student
    db.session.commit()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'phone_number' in 'field list'")
[SQL: INSERT INTO student (name, age, phone_number, gender, address) VALUES (%(name)s, %(age)s, %(phone_number)s, %(gender)s, %(address)s)]
[parameters: {'name': 'Rajesh', 'age': 21, 'phone_number': '1234567890', 'gender': None, 'address': None}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-09-28 20:51:47,517 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'phone_number' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 14, in add_student
    db.session.commit()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'phone_number' in 'field list'")
[SQL: INSERT INTO student (name, age, phone_number, gender, address) VALUES (%(name)s, %(age)s, %(phone_number)s, %(gender)s, %(address)s)]
[parameters: {'name': 'Jack Doe', 'age': 30, 'phone_number': '1234567890', 'gender': None, 'address': None}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-09-28 20:51:47,527 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'phone_number' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 14, in add_student
    db.session.commit()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'phone_number' in 'field list'")
[SQL: INSERT INTO student (name, age, phone_number, gender, address) VALUES (%(name)s, %(age)s, %(phone_number)s, %(gender)s, %(address)s)]
[parameters: {'name': 'Jill Doe', 'age': 27, 'phone_number': '1234567890', 'gender': None, 'address': None}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-09-28 21:01:36,754 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-28 21:01:36,756 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:01:36,795 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:01:36,800 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:01:36,805 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:03:53,113 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-28 21:03:53,115 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:03:53,155 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:03:53,160 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:03:53,165 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:06:16,322 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-28 21:06:16,324 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:06:16,363 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:06:16,368 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:06:16,373 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:12:11,478 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-28 21:12:11,480 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:12:11,522 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:12:11,527 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:12:11,532 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:12:27,221 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-28 21:12:27,223 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:12:27,263 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:12:27,268 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:12:27,273 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:15:24,949 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-28 21:15:24,951 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:15:24,991 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:15:24,996 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:15:25,001 - app - ERROR - Exception on /api/v1/students [POST]
Traceback (most recent call last):
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onen2n/projects/one2n-sre-bootcamp/milestone-01/app/routes.py", line 12, in add_student
    new_student = Student(name=data['name'], age=data['age'], phone_number=data['phone_number'])
                                                                           ~~~~^^^^^^^^^^^^^^^^
KeyError: 'phone_number'
2024-09-28 21:17:49,788 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-28 21:17:49,804 - app - INFO - Added student: {'age': 21, 'gender': 'male', 'id': 8, 'name': 'Rajesh'}
2024-09-28 21:17:49,815 - app - INFO - Retrieved student: {'age': 21, 'gender': 'male', 'id': 9, 'name': 'Rajesh'}
2024-09-28 21:17:49,829 - app - INFO - Updated student 10: {'age': 31, 'gender': 'male', 'id': 10, 'name': 'Jack Updated'}
2024-09-28 21:17:49,843 - app - INFO - Deleted student 11
2024-09-28 21:27:58,124 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-28 21:27:58,135 - app - INFO - Added student: {'age': 21, 'gender': 'male', 'id': 12, 'name': 'Rajesh'}
2024-09-28 21:27:58,146 - app - INFO - Retrieved student: {'age': 21, 'gender': 'male', 'id': 13, 'name': 'Rajesh'}
2024-09-28 21:27:58,159 - app - INFO - Updated student 14: {'age': 31, 'gender': 'male', 'id': 14, 'name': 'Jack Updated'}
2024-09-28 21:27:58,171 - app - INFO - Deleted student 15
2024-09-28 21:39:30,014 - app - INFO - Healthcheck endpoint test passed with message: Hi, The Web REST API Service is up and running!
2024-09-28 21:39:30,045 - app - INFO - Added student: {'age': 21, 'gender': 'male', 'id': 16, 'name': 'Rajesh'}
2024-09-28 21:39:30,063 - app - INFO - Retrieved student: {'age': 21, 'gender': 'male', 'id': 17, 'name': 'Rajesh'}
2024-09-28 21:39:30,092 - app - INFO - Updated student 18: {'age': 31, 'gender': 'male', 'id': 18, 'name': 'Jack Updated'}
2024-09-28 21:39:30,120 - app - INFO - Deleted student 19
